# Generated by Django 3.2.5 on 2021-08-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('send_page', '交易页面'), ('assert_page', '资产页面'), ('swap_page', 'swap页面'), ('set_page', '设置页面'), ('cross_page', '跨链交易页面'), ('detail_page', '资产详情页面')], max_length=20, verbose_name='页面名称')),
                ('element_name', models.CharField(max_length=20, verbose_name='元素名称')),
                ('element_description', models.CharField(blank=True, max_length=20, verbose_name='元素详情')),
                ('locate_type', models.CharField(choices=[('id', 'id'), ('class', 'class'), ('xpath', 'xpath'), ('content', 'content-desc'), ('android', 'android')], max_length=20, verbose_name='定位方法')),
                ('locate_action', models.CharField(choices=[('find_element', 'find_element'), ('find_elements', 'find_elements'), ('send', 'send'), ('click', 'click'), ('install', 'install'), ('remove', 'remove'), ('is_install', 'is_install'), ('close', 'close'), ('restart', 'restart'), ('launch', 'launch'), ('background', 'background'), ('attribute_text', 'attribute_text'), ('clipboard_text', 'clipboard_text'), ('context_desc', 'context_desc'), ('swipe_sign', 'swipe_sign')], max_length=20, verbose_name='操作动作')),
                ('locate_value', models.CharField(max_length=100, verbose_name='定位值')),
                ('locate_subscript', models.CharField(blank=True, max_length=10, verbose_name='定位下标')),
                ('locate_time', models.CharField(max_length=5, verbose_name='等待时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '页面动作管理',
                'verbose_name_plural': '页面动作管理',
            },
        ),
        migrations.CreateModel(
            name='PageScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('send_model', '交易模块'), ('assert_model', '资产模块'), ('swap_model', 'swap模块'), ('set_model', '设置模块'), ('cross_model', '跨链交易模块'), ('detail_model', '资产详情模块')], max_length=20, verbose_name='所属模块')),
                ('scene_name', models.CharField(max_length=20, verbose_name='场景名称')),
                ('scene_description', models.CharField(max_length=50, verbose_name='场景介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '场景管理',
                'verbose_name_plural': '场景管理',
            },
        ),
        migrations.CreateModel(
            name='SceneAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(blank=True, max_length=100, verbose_name='参数的key_name')),
                ('action_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLover_Ui_Test.pageaction')),
                ('scene_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLover_Ui_Test.pagescene')),
            ],
        ),
        migrations.AddField(
            model_name='pagescene',
            name='scene_actions',
            field=models.ManyToManyField(through='CLover_Ui_Test.SceneAction', to='CLover_Ui_Test.PageAction', verbose_name='场景动作列表'),
        ),
    ]
