# Generated by Django 3.2.5 on 2021-08-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CLover_Ui_Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(choices=[('app_ui_test', 'app自动化'), ('web_ui_test', 'web自动化'), ('api_test', '接口自动化')], default=True, max_length=20, verbose_name='项目名称')),
                ('project_version', models.CharField(max_length=50, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
                'ordering': ['project_name'],
                'unique_together': {('project_name', 'project_version')},
            },
        ),
        migrations.CreateModel(
            name='AppUiCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('case_description', models.CharField(max_length=100, verbose_name='用例说明')),
                ('run', models.BooleanField(default=True)),
                ('export', models.CharField(blank=True, max_length=50, verbose_name='期望结果')),
                ('assert_type', models.CharField(blank=True, max_length=50, verbose_name='断言定位类型')),
                ('assert_value', models.CharField(blank=True, max_length=50, verbose_name='断言定位值')),
                ('text_type', models.CharField(blank=True, max_length=50, verbose_name='取值类型')),
                ('assert_subscript', models.CharField(blank=True, max_length=50, verbose_name='定位下标')),
                ('param_data', models.JSONField(blank=True, verbose_name='用例参数')),
                ('case_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CLover_Ui_Test.pagescene', verbose_name='用例场景')),
                ('project_case', models.ForeignKey(limit_choices_to={'project_name': 'app_ui_test'}, on_delete=django.db.models.deletion.CASCADE, to='CLover_Ui_Test.projectversion', verbose_name='项目版本')),
            ],
            options={
                'verbose_name': 'app用例管理',
                'verbose_name_plural': 'app用例管理',
            },
        ),
    ]
