# Generated by Django 3.2.5 on 2021-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLover_Ui_Test', '0002_appuicase_projectversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuicase',
            name='assert_type',
            field=models.CharField(blank=True, choices=[('id', 'id'), ('class', 'class'), ('xpath', 'xpath'), ('content', 'content-desc'), ('android', 'android')], max_length=50, verbose_name='断言定位类型'),
        ),
    ]
