# Generated by Django 3.2.5 on 2021-08-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLover_Ui_Test', '0003_alter_appuicase_assert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_list', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
