# Generated by Django 3.2.5 on 2021-08-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLover_Ui_Test', '0004_caserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaction',
            name='key_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='参数的key_name'),
        ),
    ]
