# Generated by Django 3.2.5 on 2021-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLover_Ui_Test', '0005_pageaction_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuicase',
            name='assert_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='断言元素等待时间'),
        ),
    ]
